name: Jest

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Publish Results to Testspace
        run: |
          testspace ./results/*.xml
        if: always()
